server:
  port: 8082
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
app:
  static:
    base-url: http://localhost:8082
#    img-path: file:/Users/gbugi/Static/images/ # linux
    img-path: file:///D:/static/images/

logging:
  level:
    org.springframework.web.servlet.resource: TRACE